### ISSUE TITLE
Tomcat Server Error 

### ISSUE THREAD

**Issue by LeeGitaek** [LeeGitaek/Spring_Java_Board#1]
Several ports (8080, 8009) required by Tomcat v8.5 Server at localhost are already in use. The server may already be running in another process, or a system process may be using the port. To start this server you will need to stop the other process or change the port number(s).

**Comment by LeeGitaek** [comment]
8080 포트를 kill 로 해결 하였으나, maven 에러를 다시 얻음.

**Comment by LeeGitaek** [comment]
심각: Context initialized 이벤트를 [org.springframework.web.context.ContextLoaderListener] 클래스의 인스턴스인 리스너에 전송하는 동안 예외 발생

**Comment by LeeGitaek** [comment]
maven dependencies 등록 해주었지만 그래도 404에러

**Comment by LeeGitaek** [comment]
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: 서버 버전 이름:        Apache Tomcat/8.5.50
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: Server 빌드 시각:          Dec 7 2019 19:19:46 UTC
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: Server 버전 번호:         8.5.50.0
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: 운영체제 이름:               Mac OS X
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: 운영체제 버전:            10.15.4
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: 아키텍처:          x86_64
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: 자바 홈:             /Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: JVM 버전:           9.0.4+11
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: JVM 벤더:            Oracle Corporation
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: CATALINA_BASE:         /Users/gitaeklee/Documents/workspace-sts-3.9.11.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: CATALINA_HOME:         /usr/local/apache-tomcat-8.5.50
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: 명령 행 아규먼트: -Dcatalina.base=/Users/gitaeklee/Documents/workspace-sts-3.9.11.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: 명령 행 아규먼트: -Dcatalina.home=/usr/local/apache-tomcat-8.5.50
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: 명령 행 아규먼트: -Dwtp.deploy=/Users/gitaeklee/Documents/workspace-sts-3.9.11.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps
Jul 19, 2020 11:27:47 PM org.apache.catalina.startup.VersionLoggerListener log
정보: 명령 행 아규먼트: -Dfile.encoding=UTF-8
Jul 19, 2020 11:27:47 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
정보: 프로덕션 환경들에서 최적의 성능을 제공하는, APR 기반 Apache Tomcat Native 라이브러리가, 다음 java.library.path에서 발견되지 않습니다: [/Users/gitaeklee/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
Jul 19, 2020 11:27:48 PM org.apache.coyote.AbstractProtocol init
정보: 프로토콜 핸들러 ["http-nio-8080"]을(를) 초기화합니다.
Jul 19, 2020 11:27:48 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
정보: Using a shared selector for servlet write/read
Jul 19, 2020 11:27:48 PM org.apache.coyote.AbstractProtocol init
정보: 프로토콜 핸들러 ["ajp-nio-8009"]을(를) 초기화합니다.
Jul 19, 2020 11:27:48 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
정보: Using a shared selector for servlet write/read
Jul 19, 2020 11:27:48 PM org.apache.catalina.startup.Catalina load
정보: Initialization processed in 2041 ms
Jul 19, 2020 11:27:48 PM org.apache.catalina.core.StandardService startInternal
정보: 서비스 [Catalina]을(를) 시작합니다.
Jul 19, 2020 11:27:48 PM org.apache.catalina.core.StandardEngine startInternal
정보: Starting Servlet Engine: Apache Tomcat/8.5.50
Jul 19, 2020 11:27:50 PM org.apache.catalina.core.ApplicationContext log
정보: No Spring WebApplicationInitializer types detected on classpath
Jul 19, 2020 11:27:50 PM org.apache.jasper.servlet.TldScanner scanJars
정보: 적어도 하나의 JAR가 TLD들을 찾기 위해 스캔되었으나 아무 것도 찾지 못했습니다. 스캔했으나 TLD가 없는 JAR들의 전체 목록을 보시려면, 로그 레벨을 디버그 레벨로 설정하십시오. 스캔 과정에서 불필요한 JAR들을 건너뛰면, 시스템 시작 시간과 JSP 컴파일 시간을 단축시킬 수 있습니다.
Jul 19, 2020 11:27:51 PM org.apache.catalina.core.ApplicationContext log
정보: Initializing Spring root WebApplicationContext
INFO : org.springframework.web.context.ContextLoader - Root WebApplicationContext: initialization started
INFO : org.springframework.web.context.support.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Sun Jul 19 23:27:51 KST 2020]; root of context hierarchy
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/spring/root-context.xml]
INFO : org.springframework.beans.factory.support.DefaultListableBeanFactory - Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@3b058146: defining beans [dataSource]; root of factory hierarchy
INFO : org.springframework.beans.factory.support.DefaultListableBeanFactory - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@3b058146: defining beans [dataSource]; root of factory hierarchy
ERROR: org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource': Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'databaseType' threw exception; nested exception is java.lang.IllegalStateException: Driver for test database type [HSQL] is not available in the classpath
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1396)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1118)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:567)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:913)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:464)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:385)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:284)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'databaseType' threw exception; nested exception is java.lang.IllegalStateException: Driver for test database type [HSQL] is not available in the classpath
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:102)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:58)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1393)
	... 22 more
Jul 19, 2020 11:27:52 PM org.apache.catalina.core.StandardContext listenerStart
심각: Context initialized 이벤트를 [org.springframework.web.context.ContextLoaderListener] 클래스의 인스턴스인 리스너에 전송하는 동안 예외 발생
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource': Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'databaseType' threw exception; nested exception is java.lang.IllegalStateException: Driver for test database type [HSQL] is not available in the classpath
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1396)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1118)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:567)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:913)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:464)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:385)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:284)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'databaseType' threw exception; nested exception is java.lang.IllegalStateException: Driver for test database type [HSQL] is not available in the classpath
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:102)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:58)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1393)
	... 22 more

Jul 19, 2020 11:27:52 PM org.apache.catalina.core.StandardContext startInternal
심각: 하나 이상의 리스너들이 시작하지 못했습니다. 상세 내역은 적절한 컨테이너 로그 파일에서 찾을 수 있습니다.
Jul 19, 2020 11:27:52 PM org.apache.catalina.core.StandardContext startInternal
심각: 이전 오류들로 인해 컨텍스트 [/mvc]의 시작이 실패했습니다.
Jul 19, 2020 11:27:52 PM org.apache.catalina.core.ApplicationContext log
정보: Closing Spring root WebApplicationContext
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/local/apache-tomcat-8.5.50/lib/catalina.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jul 19, 2020 11:27:52 PM org.apache.coyote.AbstractProtocol start
정보: 프로토콜 핸들러 ["http-nio-8080"]을(를) 시작합니다.
Jul 19, 2020 11:27:52 PM org.apache.coyote.AbstractProtocol start
정보: 프로토콜 핸들러 ["ajp-nio-8009"]을(를) 시작합니다.
Jul 19, 2020 11:27:52 PM org.apache.catalina.startup.Catalina start
정보: Server startup in 4542 ms

**Comment by LeeGitaek** [comment]
=> 문제의 코드


	<jdbc:embedded-database id="dataSource" type="HSQL">
		<jdbc:script location = "classpath:BoardSchema.sql" />
		<jdbc:script location = "classpath:BoardData.sql" />
	</jdbc:embedded-database>	


root-context.xml 의 위 부분을 주석 처리한 후 실행 성공

**Comment by LeeGitaek** [comment]
<jdbc:embedded-database id="dataSource" type="HSQL">
		<jdbc:script location = "classpath:/**/BoardSchema.sql" />
		<jdbc:script location = "classpath:/**/BoardData.sql" />
	</jdbc:embedded-database>	


문제의 코드에서
class path 에 대한 경로 설정을 build path 를 통해 파악하여 
와일드 카드 ** 로 처리를 하여 성공적으로 에러를 해결하였음.
